// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('SystemAccess', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('SystemAccess', async function() {
    await driver.get("https://code-leap-network.vercel.app/")
    await driver.manage().window().setRect({ width: 1280, height: 1080 })
    await driver.findElement(By.name("username")).click()
    await driver.findElement(By.name("username")).sendKeys("tnrv")
    await driver.findElement(By.css(".sc-bczRLJ")).click()
    {
      const element = await driver.findElement(By.css(".sc-bczRLJ"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".sc-kDDrLX")).click()
  })
})
